<a href="https://colab.research.google.com/github/ehsung/PUBH6886/blob/main/PUBH6886_RLabs5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PUBH 6886: R Lab 05

## Edward Sung

## 10/01/24

# 4.7.3 Linear Discriminant Analysis

>[4.7.3 Linear Discriminant Analysis](#updateTitle=true&folderId=1r-g8wJfeKaGd9a8yLWY3NoKaegmzbrzB&scrollTo=nmLE82RzaYmA)

>[4.7.4 Quadratic Discriminant Analysis](#updateTitle=true&folderId=1r-g8wJfeKaGd9a8yLWY3NoKaegmzbrzB&scrollTo=1ZE_WcbObV70)

>[4.7.5 Naive Bayes](#updateTitle=true&folderId=1r-g8wJfeKaGd9a8yLWY3NoKaegmzbrzB&scrollTo=-64cysP1bhRp)



In [5]:
lda = LDA(store_covariance=True)

In [6]:
X_train, X_test = [M.drop(columns=['intercept'])
for M in [X_train , X_test]]
lda.fit(X_train , L_train)

LinearDiscriminantAnalysis(store_covariance=True)

In [7]:
lda.means_

array([[ 0.04279022,  0.03389409],
       [-0.03954635, -0.03132544]])

In [8]:
lda.classes_

array(['Down', 'Up'], dtype='<U4')

In [9]:
lda.priors_

array([0.49198397, 0.50801603])

In [11]:
lda.scalings_

array([[-0.64201904],
       [-0.51352928]])

In [12]:
lda_pred = lda.predict(X_test)

In [13]:
confusion_table(lda_pred , L_test)

Truth      Down   Up
Predicted           
Down         35   35
Up           76  106

In [14]:
lda_prob = lda.predict_proba(X_test)
np.all(np.where(lda_prob[:,1] >= 0.5, 'Up','Down') == lda_pred)

True

In [16]:
np.all([lda.classes_[i] for i in np.argmax(lda_prob , 1)] == lda_pred)

True

In [17]:
np.sum(lda_prob[:,0] > 0.9)

0

# 4.7.4 Quadratic Discriminant Analysis

In [18]:
qda = QDA(store_covariance=True)
qda.fit(X_train , L_train)

QuadraticDiscriminantAnalysis(store_covariance=True)

In [19]:
qda.means_ , qda.priors_

(array([[ 0.04279022,  0.03389409],
        [-0.03954635, -0.03132544]]),
 array([0.49198397, 0.50801603]))

In [20]:
qda.covariance_[0]

array([[ 1.50662277, -0.03924806],
       [-0.03924806,  1.53559498]])

In [21]:
qda_pred = qda.predict(X_test)
confusion_table(qda_pred , L_test)

Truth      Down   Up
Predicted           
Down         30   20
Up           81  121

In [22]:
np.mean(qda_pred == L_test)

0.5992063492063492

# 4.7.5 Naive Bayes

In [23]:
NB = GaussianNB()
NB.fit(X_train , L_train)

GaussianNB()

In [24]:
NB.classes_

array(['Down', 'Up'], dtype='<U4')

In [25]:
NB.class_prior_

array([0.49198397, 0.50801603])

In [26]:
NB.theta_

array([[ 0.04279022,  0.03389409],
       [-0.03954635, -0.03132544]])

In [27]:
NB.var_

array([[1.50355429, 1.53246749],
       [1.51401364, 1.48732877]])

In [28]:
X_train[L_train == 'Down'].mean()

Lag1    0.042790
Lag2    0.033894
dtype: float64

In [29]:
X_train[L_train == 'Down'].var(ddof=0)

Lag1    1.503554
Lag2    1.532467
dtype: float64

In [30]:
nb_labels = NB.predict(X_test)
confusion_table(nb_labels , L_test)

Truth      Down   Up
Predicted           
Down         29   20
Up           82  121

In [31]:
NB.predict_proba(X_test)[:5]

array([[0.4873288 , 0.5126712 ],
       [0.47623584, 0.52376416],
       [0.46529531, 0.53470469],
       [0.47484469, 0.52515531],
       [0.49020587, 0.50979413]])