# PUBH 6886: R Lab 01

##Edward Sung

##9/3/24

In [12]:
import pandas as pd
import numpy as np

###1 Vectors and Matrices

In [13]:
a = [1,2,4,5]

a

[1, 2, 4, 5]

In [14]:
A = np.array([[1,2,3],[4,5,6]])

A

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
A_t = A.T

A_t

array([[1, 4],
       [2, 5],
       [3, 6]])

In [16]:
A.shape

(2, 3)

###2 Matrix Addition and Scalar Multiplication

In [20]:
U = np.array([[2,-2,1],[4,8,-1],[-1,2,6]])
V = np.array([[3,1,-1],[-1,2,9],[-8,3,3]])

U + V

array([[ 5, -1,  0],
       [ 3, 10,  8],
       [-9,  5,  9]])

###3 Matrix Multiplication

In [23]:
G = np.array([[1,-2,0],[-1,3,2]])
H = np.array([[3,1,-1],[-1,2,7],[-4,3,1]])

np.dot(G,H)

array([[  5,  -3, -15],
       [-14,  11,  24]])

###4 Determinant of a Matrix

In [27]:
np.linalg.det(V)

-144.99999999999997

###5 Inverse of a Matrix

In [32]:
K = np.array([[-1,3],[2,-2]])

K_inv = np.linalg.inv(K)
K_inv

array([[0.5 , 0.75],
       [0.5 , 0.25]])

In [33]:
np.dot(K, K_inv)

array([[1., 0.],
       [0., 1.]])

###6 Eigenvalues and Eigenvectors

In [35]:
eigenvalues, eigenvectors = np.linalg.eig(V)

In [36]:
eigenvalues

array([ 6.73078792,  5.31921084, -4.04999876])

In [37]:
eigenvectors

array([[ 0.10803432,  0.23460132,  0.1937779 ],
       [ 0.87498877,  0.90329186, -0.80408166],
       [ 0.47193563,  0.35920194,  0.56205232]])

###7 Mean Vector, Variance-Covariance Matrix, Scaling

In [39]:
lbwt_data = pd.read_csv("/content/lowbwt.csv")

lbwt_data.head()

sbp  gestage  apgar5
0   43       29       7
1   51       31       8
2   42       33       0
3   39       31       8
4   48       30       7

In [40]:
lbwt_data.apply(pd.Series.mean, axis=0)

sbp        47.08
gestage    28.89
apgar5      6.25
dtype: float64

In [43]:
lbwt_data.cov()

sbp   gestage    apgar5
sbp      130.033939  8.120000  4.121212
gestage    8.120000  6.422121  1.047980
apgar5     4.121212  1.047980  5.906566

In [45]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

lbwt_data_scl = scaler.fit_transform(lbwt_data)

In [47]:
scaler.mean_

array([47.08, 28.89,  6.25])

In [48]:
scaler.scale_

array([11.34608302,  2.52148766,  2.41816046])

In [51]:
pd.DataFrame(lbwt_data_scl, columns=lbwt_data.columns).mean()

sbp        1.554312e-16
gestage   -2.253753e-16
apgar5     1.887379e-17
dtype: float64

In [53]:
pd.DataFrame(lbwt_data_scl, columns=lbwt_data.columns).cov()

sbp   gestage    apgar5
sbp      1.010101  0.283827  0.150208
gestage  0.283827  1.010101  0.171874
apgar5   0.150208  0.171874  1.010101

###8 Distance

In [56]:
M = np.array([[1,5,-1],[-2,3,2]])

M

array([[ 1,  5, -1],
       [-2,  3,  2]])

In [66]:
from scipy.spatial.distance import pdist, squareform, euclidean

euclidean(M[0], M[1])

4.69041575982343

In [67]:
u = np.array([1, 5, -1])
v = np.array([-2, 3, 2])

squared_differences = (u - v) ** 2

np.sqrt(np.sum(squared_differences))

4.69041575982343

In [68]:
M = np.array([[1, 5, -1],
              [-2, 3, 2],
              [0, 1, -3],
              [3, -1, 8]])

M

array([[ 1,  5, -1],
       [-2,  3,  2],
       [ 0,  1, -3],
       [ 3, -1,  8]])

In [71]:
np.tril(squareform(pdist(M, metric='euclidean')), k=-1)

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 4.69041576,  0.        ,  0.        ,  0.        ],
       [ 4.58257569,  5.74456265,  0.        ,  0.        ],
       [11.        ,  8.77496439, 11.5758369 ,  0.        ]])